Add Scylla Monitoring Stack landing page
scylladb/scylla-monitoring pull request #1447
Opened 2021-06-16 11:46 UTC by lauranovich

replaces https://github.com/scylladb/scylla-monitoring/pull/1442
FIXES #1345

Adds a landing page to the Scylla Monitoring stack docs site
Moves intro content to its own file
Adds mascot and topic boxes

BEFORE
![Screenshot from 2021-06-16 14-35-53](https://user-images.githubusercontent.com/36125151/122213399-92103100-ceb1-11eb-8e31-b6faeb6d9ca3.png)

AFTER
![Screenshot from 2021-06-16 14-36-32](https://user-images.githubusercontent.com/36125151/122213412-963c4e80-ceb1-11eb-944d-fba89ca69429.png)

2021-06-16 11:47 UTC, lauranovich commented
I was able to build a multiversion with no errors - it is just not pictured above

2021-06-16 11:50 UTC, lauranovich commented
If possible we should backport this change

2021-06-16 13:21 UTC, tzach commented
LGTM

2021-06-17 11:12 UTC, dgarcia360 requested changes

2021-06-17 11:12 UTC, dgarcia360 commented on docs/source/index.rst
> +
````suggestion
.. title:: Scylla Monitoring Stack

.. raw:: html

  <div class="full-contents">

.. raw:: html

  <div class="main-title">
    <img class="main-title-logo" src="_static/img/scylla-monitor.png" />
    <div class="main-title-header">
      <h1>Scylla Monitoring Stack</h1>
      <h3>Complete NoSQL monitoring solution for your Scylla database clusters.</h3>
    </div>
  </div>
  
````

2021-06-17 11:12 UTC, dgarcia360 commented on docs/source/index.rst
>  .. include:: /_common/monitor-description.rst
```suggestion
```

2021-06-17 11:12 UTC, dgarcia360 commented on docs/source/index.rst
> +  </div>
```suggestion
  </div></div>
```

2021-06-17 11:13 UTC, dgarcia360 commented
After reviewing the PR, I'd add a few modifications so that the landing page look and feel is more aligned with other projects  (scylla-docs, sphinx-scylladb-theme):

![image](https://user-images.githubusercontent.com/9107969/122384264-6fd6eb80-cf63-11eb-9c26-a7850c1a9caf.png)

To apply the changes:

1. Accept the suggestions proposed as comments.

2. In ``conf.py``, apply the following configuration changes:

- Under ``html_theme_options``, set ``'show_sidebar_index': False,``

- Replace the lines:

```
html_theme = 'sphinx_scylladb_theme'
html_style = ''
````
With:

```
html_theme = 'sphinx_scylladb_theme'
html_static_path = ['_static']
````

3. Under ``docs/source``, create a new directory ``_static/img``. Then, move ``scylla-monitor.png`` under ``_static/img/scylla-monitor.png``.

2021-06-17 13:42 UTC, lauranovich commented
Now this is an improvement - thank you David for the review
![Screenshot from 2021-06-17 16-42-20](https://user-images.githubusercontent.com/36125151/122408422-0cf94a80-cf8b-11eb-8927-50beb8e3e553.png)

2021-06-17 13:43 UTC, lauranovich commented
@amnonh please merge this and backport as far as you can go.

2021-06-17 13:57 UTC, dgarcia360 commented
@lauranovich I don't recommend to backport yet - I'd wait until we release the new design to avoid doing it twice.

2021-06-17 14:20 UTC, merged